version: '3.8'
services:
  db:
    image: "postgres:13.5"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "api_biblioteca"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  server:
    image: my-server
    build:
      context: .
      dockerfile: /Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=local
      - APP_DSN=postgres://127.0.0.1/api_biblioteca?sslmode=disable&user=postgres&password=postgres
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    depends_on:
     - db

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1